name: chiddiya_udd
description: Toyathon 2021 Project Team Archit

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^2.1.0
  introduction_screen: ^1.0.9
  simple_animations: ^1.3.4
  firebase_auth: ^0.14.0+5
  firebase_core: ^0.4.0
#  cupertino_icons: ^1.0.1
  splashscreen: ^1.3.5
  provider: ^3.1.0
  flutter_spinkit: ^4.1.2
  cloud_firestore: ^0.12.9+4
  shrink_sidemenu: ^1.0.0+3
  liquid_ui: ^1.0.0+9
  slimy_card: ^1.0.4
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
#  integration_test:
#    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/